services:
  postgres:
    image: postgres:latest
    container_name: tokopeida-postgres
    environment:
      POSTGRES_DB: tokopeida
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: tokopeida-backend
    build:
      context: ./backend
      target: final
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/tokopeida?sslmode=disable
      - PORT=3001
      - JWT_KEY=dqu5dUcWkazVXcnAUU5pSBvftQQHDzWtHqWe6GICNlQ
      - DOMAIN=http://localhost

  frontend:
    container_name: tokopeida-frontend
    build:
      context: ./frontend
      target: final
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_DOMAIN=http://localhost
      - PORT=3000

  nginx:
    container_name: tokopeida-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
