import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import UserProvider from "@/app/user-provider"
import StoreProvider from "@/app/store-provider"
import { useServerFetch } from "@/hooks/useServerFetch"
import { user, userApiResponse } from "@/interfaces/user"
import { store, storeApiResponse } from "@/interfaces/store"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Tokopeida",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let user: user | null = null
  let userResponse: userApiResponse | null = null

  try {
    userResponse = (
      await useServerFetch.get<userApiResponse>("/api/user/current")
    ).data
  } catch (err) {
    console.log(err)
  }

  if (userResponse) {
    user = {
      email: userResponse.email,
      firstName: userResponse.first_name,
      lastName: userResponse.last_name,
      balance: userResponse.balance,
      createdAt: new Date(userResponse.created_at),
      updatedAt: new Date(userResponse.updated_at),
    }
  }

  let store: store | null = null
  let storeResponse: storeApiResponse | null = null

  try {
    storeResponse = (
      await useServerFetch.get<storeApiResponse>("/api/store/current")
    ).data
  } catch (err) {
    console.log(err)
  }

  if (storeResponse) {
    store = {
      id: storeResponse.id,
      name: storeResponse.name,
      createdAt: new Date(storeResponse.created_at),
      updatedAt: new Date(storeResponse.updated_at),
    }
  }

  return (
    <html lang="en">
      <StoreProvider initialStore={store}>
        <UserProvider initialUser={user}>
          <body className={inter.className}>
            {children}
            <Toaster />
          </body>
        </UserProvider>
      </StoreProvider>
      s
    </html>
  )
}
